### ISSUE TITLE
is the communication non-blocking?

### ISSUE THREAD

**Issue by gondo** [slawomir-pryczek/HSServer#1]
if multiple php processes starts communication with your golang server, are these processes blocked and executed one by one or in parallel?

**Comment by slawomir-pryczek** [comment]
Hi Gondo, the server runs in paralell by default, so you can have as many calls processed simultaneously as you like and you don't need to do anything.

http://www.screencast.com/t/aCqjk6hllf
http://www.screencast.com/t/q3R5UOINOpk

You can also modify your callback easily to add critical section (like mutex) to make it single-threaded and process one-by-one.

There's also a way of making it asynchronous, you just need to include __skipsendback=>true in $data, this way you don't even need to wait for golang to finish processing (eg. if you want to write a daemon that'll collect data in background, or you need to make request and collect data later). So the communication model is very flexible ;)
