### ISSUE TITLE
gRPC

### ISSUE THREAD

**Issue by pjebs** [slawomir-pryczek/HSServer#2]
I was wondering what the difference was between this project and gRPC:

https://grpc.io/docs/quickstart/php.html
https://grpc.io/docs/quickstart/go.html

**Comment by slawomir-pryczek** [comment]
Hey, so basically after looking at these docs briefly, main differences are:

- You don't need to install additional php extension to use it. One of the reasons to write it was, that php memcached extension was very buggy for PHP7 for very long time, it was working fine for low traffic websites but for high traffic apps it was segfaulting like crazy back then (probably they fixed it now). Also when reading about some other clients (eg. redis) it seems they also have issues, mainly resulting from internal PHP api changes between versions. PHP has great psockets implementation, and also many great compression plugins... so the idea was to just write client in php, and this itself makes many potential problems gone.

- You have very nice server-status built-in, that's usable for debugging / diagnostics and it works more like server (is accessible through standard HTTP or TCP/UDP calls for example)
https://www.screencast.com/t/wKY5v6ehJ

- Data marshalling is done on server side not on the client (so you can call all services via http, and it's very simple to define services as you're sending text)

- No routing / load balancing functionality

So basically it seems there's a lot needed to start with gRPC, to start with HSSserver you just need to copy files from php-client to your php project, and copy files from /go/src for your golang server. Then you can go to HSServer/go/src/simple_server/ and start adding your code. And it's very debugging-friendly, you can go to eg. http://127.0.0.1/?action=server-status or http://127.0.0.1/?action=echo&data=1234567, same thing as calling server-status / echo service using sockets API from PHP.

We also considered 0mq (which is great), but we needed something coupled with PHP, locally as we're doing LB / request routing on higher level. So this project is something mainly designed for very clear use case - moving slow PHP code to Golang quickly ...

If you want to use it somewhere I can help you get started, code is production ready and serving billions of requests daily.
